services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./Docker/data/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    container_name: clommercy-database
    restart: always
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ClommercySqlPass123!
      - MSSQL_PID=Developer
volumes:
 sqlserver-data: